name: Compile and Release v2
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.1
          cache: 'npm'

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: npm i

      - name: Package into node binary
        run: |
          ./node_modules/.bin/esbuild ./src/index.js --bundle --platform=node --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js --target=node22 --outfile=out.cjs
          deno compile -A --exclude node_modules --target x86_64-pc-windows-msvc out.cjs -o build/WA2DC.exe
          deno compile -A --exclude node_modules --target x86_64-apple-darwin out.cjs -o build/WA2DC-macOS
          deno compile -A --exclude node_modules --target aarch64-apple-darwin out.cjs -o build/WA2DC-macOS-arm64
          deno compile -A --exclude node_modules --target x86_64-unknown-linux-gnu out.cjs -o build/WA2DC-Linux
          deno compile -A --exclude node_modules --target aarch64-unknown-linux-gnu out.cjs -o build/WA2DC-Linux-arm64
          exit 0
        shell: bash

      - name: Create Signature
        uses: FKLC/sign-files-action@v1.0.0
        with:
          privateKey: ${{ secrets.PK }}
          passphrase: ${{ secrets.PK_PASSPHRASE }}
          outputFolder: build/
          files: |
            build/**

      - name: Make a draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: build/**
