name: Build Linux Binary
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    # upload-artifact needs actions: write; keep contents read-only
    permissions:
      contents: read
      actions: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Linux binary
        run: |
          ./node_modules/.bin/esbuild src/index.js \
            --bundle --platform=node \
            --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js \
            --target=node18 --outfile=out.js

          ./node_modules/.bin/pkg out.js \
            -t latest-linux-x64 --options no-warnings \
            -o build/WA2DC-Linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WA2DC-Linux
          path: build/WA2DC-Linux
          if-no-files-found: error
