name: Compile and Release v2
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Package into node binary
        run: |
          ./node_modules/.bin/esbuild ./src/index.js --bundle --platform=node --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js --target=node18 --outfile=out.js
          ./node_modules/.bin/pkg out.js -t latest-linux-x64 --options no-warnings -o build/WA2DC-Linux
          ./node_modules/.bin/pkg out.js -t latest-macos-x64 --options no-warnings -o build/WA2DC-macOS
          ./node_modules/.bin/pkg out.js -t latest-win-x64 --options no-warnings -o build/WA2DC
          ./node_modules/.bin/pkg out.js -t latest-linux-arm64 --options no-warnings -o build/WA2DC-Linux-arm64
          ./node_modules/.bin/pkg out.js -t latest-macos-arm64 --options no-warnings -o build/WA2DC-macOS-arm64
          ./node_modules/.bin/pkg out.js -t latest-win-arm64 --options no-warnings -o build/WA2DC-arm64
          exit 0
        shell: bash

      - name: Create Signature
        uses: FKLC/sign-files-action@v1.0.0
        with:
          privateKey: ${{ secrets.PK }}
          passphrase: ${{ secrets.PK_PASSPHRASE }}
          outputFolder: build/
          files: |
            build/**

      - name: Make a draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: build/**
