name: Build Linux Binary
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'   # Node 22 is LTS; 20 also works
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Linux binary
        run: |
          npx esbuild src/index.js \
            --bundle --platform=node --format=cjs \
            --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js \
            --target=node22 --outfile=out.js

          # Use the maintained fork that supports Node 20/22 targets
          npx -y @yao-pkg/pkg out.js \
            -t node22-linux-x64 --options no-warnings \
            -o build/WA2DC-Linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WA2DC-Linux
          path: build/WA2DC-Linux
          if-no-files-found: error
