name: Build Linux Binary
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create/update releases
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Linux binary
        run: |
          npx esbuild src/index.js \
            --bundle --platform=node --format=cjs \
            --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js \
            --target=node22 --outfile=out.js

          npx -y @yao-pkg/pkg out.js \
            -t node22-linux-x64 --options no-warnings \
            -o build/WA2DC-Linux

      - name: Create checksum
        run: sha256sum build/WA2DC-Linux > build/WA2DC-Linux.sha256

      - name: Upload artifact (for CI browsing)
        uses: actions/upload-artifact@v4
        with:
          name: WA2DC-Linux
          path: |
            build/WA2DC-Linux
            build/WA2DC-Linux.sha256
          if-no-files-found: error

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/WA2DC-Linux
            build/WA2DC-Linux.sha256
