name: Build Linux & Windows Binaries
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build with esbuild
        run: |
          npx esbuild src/index.js \
            --bundle --platform=node --format=cjs \
            --external:sharp --external:qrcode-terminal --external:jimp --external:link-preview-js \
            --target=node22 --outfile=out.js

      - name: Package binaries (Linux & Windows)
        run: |
          mkdir -p build

          # Linux x64
          npx -y @yao-pkg/pkg out.js \
            -t node22-linux-x64 --options no-warnings \
            -o build/WA2DC-Linux

          # Windows x64 — disable bytecode to avoid needing to run the Win exe on Linux
          npx -y @yao-pkg/pkg out.js \
            -t node22-win-x64 --options no-warnings \
            --no-bytecode --public-packages "*" --public \
            -o build/WA2DC.exe

      - name: Create checksums
        run: |
          sha256sum build/WA2DC-Linux  > build/WA2DC-Linux.sha256
          sha256sum build/WA2DC.exe    > build/WA2DC.exe.sha256

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WA2DC-binaries
          path: |
            build/WA2DC-Linux
            build/WA2DC-Linux.sha256
            build/WA2DC.exe
            build/WA2DC.exe.sha256
          if-no-files-found: error

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            build/WA2DC-Linux
            build/WA2DC-Linux.sha256
            build/WA2DC.exe
            build/WA2DC.exe.sha256
